---
    - hosts: all
    
      tasks:

      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
        become: yes
      
      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present
        become: yes

      - name: ensure the jenkins apt repository key is installed
        apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
        become: yes

      - name: Install required system packages
      apt: 
        name:
          - git
          - apt-transport-https
          - ca-certificates
          - wget
          - software-properties-common
          - gnupg2
          - curl
        become: yes

      - name: Install Docker Module for Python
        pip:
          name: docker
        become: yes
 
            
      
