---
    - hosts: all
    
      tasks:
      - name: Update APT package manager repositories cache
        become: true
        apt:
          update_cache: yes
      
      - name: ensure the repository is configured
        apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
        become: yes
    
      - name: Install OpenJDK Java
        become: yes
        apt:
          name: "{{ item }}"
          state: present
        with_items:
         openjdk-8-jdk
      
      - name: ensure jenkins is installed
         apt: name=jenkins update_cache=yes
         become: yes
   
     - name: ensure jenkins is running
         service: name=jenkins state=started
...